// Exercise image map - auto-generated by scripts/fetchExerciseImages.ts
// This file will be overwritten when you run: npm run fetch-images
// Until then, it provides an empty map so the app doesn't break

export const exerciseImageMap: Record<string, string> = {};

export function getExerciseImage(exerciseName: string): string | undefined {
  return exerciseImageMap[exerciseName];
}





